export const JOYRIDE_STYLES = {
  arrow: {
    color: '#ffffff',
  },
  tooltip: {
    backgroundColor: '#ffffff',
    border: '3px solid #000',
    borderRadius: 0,
    boxShadow: '8px 8px 0px 0px rgba(0,0,0,1)',
    padding: '20px 22px',
  },
  tooltipContainer: {
    textAlign: 'left',
  },
  tooltipTitle: {
    fontFamily: "'Bebas Neue', cursive",
    fontSize: '24px',
    fontWeight: 900,
    letterSpacing: '0.02em',
    lineHeight: 1.1,
    color: '#000000',
    textTransform: 'uppercase',
    textAlign: 'left',
    marginBottom: 8,
    padding: 0,
  },
  tooltipContent: {
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: '13px',
    fontWeight: 500,
    lineHeight: 1.55,
    color: '#374151',
    textAlign: 'left',
    padding: 0,
  },
  tooltipFooter: {
    marginTop: 16,
    alignItems: 'center',
  },
  tooltipFooterSpacer: {
    flex: 1,
  },
  buttonBack: {
    backgroundColor: '#ffffff',
    border: '3px solid #000',
    borderRadius: 0,
    boxShadow: '3px 3px 0px 0px rgba(0,0,0,1)',
    color: '#6b7280',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: 900,
    fontSize: '11px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    padding: '8px 16px',
    marginRight: 8,
  },
  buttonPrimary: {
    backgroundColor: '#FF6B35',
    border: '3px solid #000',
    borderRadius: 0,
    boxShadow: '3px 3px 0px 0px rgba(0,0,0,1)',
    color: '#ffffff',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: 900,
    fontSize: '11px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    padding: '8px 18px',
  },
  buttonSkip: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#9ca3af',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: 900,
    fontSize: '11px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    textDecoration: 'underline',
    textUnderlineOffset: 3,
  },
  buttonClose: {
    color: '#000000',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '18px',
    fontWeight: 900,
    lineHeight: 1,
  },
  overlay: {
    backgroundColor: 'rgba(20, 13, 8, 0.72)',
  },
  floater: {
    maxWidth: 420,
  },
  loader: {
    color: '#FF6B35',
  },
}